# Generated by Django 5.2.1 on 2025-06-08 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Заголовок публикации"
                    ),
                ),
                ("content", models.TextField(verbose_name="Описание публикации")),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если публикация платная",
                        verbose_name="Платная публикация",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("free", "Бесплатно"),
                            ("subscription", "По подписке"),
                            ("paid", "Платная публикация"),
                        ],
                        default="free",
                        max_length=12,
                        verbose_name="Тип доступа",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Укажите дату покупки",
                        verbose_name="Дата покупки",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Укажите стоимость покупки",
                        verbose_name="Стоимость покупки",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        default="initial_value",
                        help_text="Укажите ID сессии",
                        max_length=255,
                        null=True,
                        verbose_name="ID сессии",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на оплату",
                        max_length=400,
                        null=True,
                        verbose_name="Ссылка на оплату",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка публикации",
                "verbose_name_plural": "Покупки публикаций",
            },
        ),
    ]
