# Generated by Django 5.2.1 on 2025-06-08 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите владельца публикации",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец публикации",
            ),
        ),
        migrations.AddField(
            model_name="postpurchase",
            name="post",
            field=models.ForeignKey(
                help_text="Укажите публикацию",
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
                verbose_name="Публикация",
            ),
        ),
        migrations.AddField(
            model_name="postpurchase",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователь",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
